apiVersion: v1
kind: Pod
metadata:
  name: ngt-session-@SESSION_ID@
  labels:
    home-afs: "true" 
    mount-cvmfs: "true" 
    mount-afs: "true" 
spec:
  containers:
  - name: container
    image: registry.cern.ch/ngt/lxplus-like:9
    command: ["sleep", "infinity"] 
    resources:
      limits:
        nvidia.com/gpu: @GPU_COUNT@
  nodeSelector:
    nvidia.com/gpu.product: @NVIDIA_GPU@
