name: test-changes
on:
  push:
    paths:
      - jenkins/parser/jobs-config.json
  pull_request:
    paths:
      - jenkins/parser/jobs-config.json
jobs:
  configfile-sanity-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checking job's configuration in parser job
        run: PYTHONPATH=. python jenkins/parser/paser-config-unittest.py
